# Site settings
title: Path Finder Documentation
description: Documentation for network flow algorithms implementation on Circles
baseurl: "/pathfinder-docs" 
url: "https://hdser.github.io" 

# Build settings
remote_theme: pmarsceill/just-the-docs

# Theme settings
color_scheme: light
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/hdser/pathfinder-docs"

# Footer content
footer_content: "Copyright &copy; 2024 hdser. Distributed by an <a href=\"https://github.com/hdser/pathfinder-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Collections for organizing content
collections:
  theoretical_background:
    permalink: "/:collection/:path/"
    output: true
  original_implementation:
    permalink: "/:collection/:path/"
    output: true
  new_implementation:
    permalink: "/:collection/:path/"
    output: true
  benchmark_tests:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    theoretical_background:
      name: Theoretical Background
    original_implementation:
      name: Original Implementation
    new_implementation:
      name: New Implementation
    benchmark_tests:
      name: Benchmark Tests